### ISSUE TITLE
Update hackthis plugin

### ISSUE THREAD

**Issue by lwward** [tehron/tehbot#4]
HackThis!! has moved to Defend the Web and the plugin needs to be updated. 

There is a new API which might streamline things: https://defendtheweb.net/help/developers/api-documentation

**Comment by tehron** [comment]
Will fix soon. The API seems cool. But there is no way to retrieve a post (content), is there?

**Comment by lwward** [comment]
Not currently. Happy to add if it will be useful?

**Comment by tehron** [comment]
Didn't use the API after all to have more control what I get instead of requesting from you to add xyz to the API.
Should work again!
